### ISSUE TITLE
Feature Suggestion: Configurable Default settings via yaml configs

### ISSUE THREAD

**Issue by True-Demon** [EmpireProject/Empire#1104]
So, some colleagues and I have been playing with some of the features in Empire and noticed that there are certain settings in the listeners, stagers, and such that we frequently keep changing. Originally, I had the idea to just change the defaults by overwriting the lib/stagers/path/to/stager.py, but I quickly realized that everything I changed would get reverted with subsequent pulls from github.

For example, if I wanted to change the multi/launcher.py so that SafeChecks are turned off by default to shorten the payload, I could go and change SafeChecks default value to "False"

```
...
            'SafeChecks' : {
                'Description'   :   'Switch. Checks for LittleSnitch or a SandBox, exit the staging process if true. Defaults to True.',
                'Required'      :   True,
                'Value'         :   'True'
            },    
...
```
What would be cool is if we could adjust these configurations ourselves and keep them saved in a config file so that we could modify default values that we like to set on our engagements. I had an idea to create custom config files that empire could parse and set new default settings for its various listeners, stagers, and such that was suited to the user's preferences. 

Better yet, it would be awesome if we could use this to build custom stagers and listeners based on existing modules, but setting custom values to the options. These custom configurations could be based around certain types of assessments, emphasizing stealth, or where stealth isn't a priority, or even have special configurations specific to your clients. 

Users could set up multiple configuration files so that they could call different defaults from configuration files from the command line like so:
`./empire via --config red-team_config.yml`
`./empire via --config loud_config.yml`
`./empire via --config client-name_project1000_config.yml`

In my_config.yml file, I would structure it like so...
```
stagers:
   multi:
      no_checks_launcher: launcher         # Takes its base configuration from the launcher.py stager
         Author: 'Someone'
         Description: 'Generates a launcher without safe checks.'
         Comments: ['']
         Options:
            Listener:
               Description: 'Listener to generate stager for.'
               Required: True
               Value: 'Default'

            SafeChecks:
               Description: 'Switch. Checks for LittleSnitch or a SandBox, exit the staging process if true. Defaults to True.'
               Required: True
               Value: True
# ... truncated
```
By default, values that aren't defined in the config.yml file would fall back to what is already pre-built into the lib files, so you could either have a very short configuration, or you could fully customize

Users could get creative with this as they like, but the main thing I'm getting at is ease of use and flexibility. The reason I'm creating this issue is that it would be quite a lot of work, but I am highly interested in contributing this to the project so that myself and others could make use of it. I think it would add an extra layer of customization that red-teamers could make use of. It would enable customized listeners, launchers, stagers, etc to be created and customized from a single file rather than having to go into multiple files every time they pull down the latest updates and change the defaults to suit their preferences.

Like I said, I am interested in contributing to the project, but since this feature I have in mind would be quite an undertaking, I wanted to create an issue and get a consensus from the Empire devs to see how you feel about it. Would be a shame to do all the work and have the PR rejected, lol.
